// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaznQqCUufVlybaZ80EOEsu92zTSJh4sg',
    appId: '1:345503533505:web:cbd28564bc800381f9c740',
    messagingSenderId: '345503533505',
    projectId: 'medtest-e1117',
    authDomain: 'medtest-e1117.firebaseapp.com',
    storageBucket: 'medtest-e1117.appspot.com',
    measurementId: 'G-WZ5FBS06S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCegBtELwOQh9WjmhXTPtgONYp7HRF2ujw',
    appId: '1:345503533505:android:2a24c8a34a380828f9c740',
    messagingSenderId: '345503533505',
    projectId: 'medtest-e1117',
    storageBucket: 'medtest-e1117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh_MVmqc1OgPnHwYuOn11NuvGMX7fV0gg',
    appId: '1:345503533505:ios:aece9d753d944729f9c740',
    messagingSenderId: '345503533505',
    projectId: 'medtest-e1117',
    storageBucket: 'medtest-e1117.appspot.com',
    iosBundleId: 'com.example.medtestInsight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh_MVmqc1OgPnHwYuOn11NuvGMX7fV0gg',
    appId: '1:345503533505:ios:c78a4c0c5817dd6bf9c740',
    messagingSenderId: '345503533505',
    projectId: 'medtest-e1117',
    storageBucket: 'medtest-e1117.appspot.com',
    iosBundleId: 'com.example.medtestInsight.RunnerTests',
  );
}
